# Generated by Django 2.0.4 on 2018-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymeta',
            options={'ordering': ('-date_recorded',)},
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='date_recorded',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Recorded'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='soil_moisture_state',
            field=models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
